export const PRODUCTION_UNITS = [
  { label: "Ha", value: "Ha" },
  { label: "Batang", value: "Batang" },
  { label: "Kg", value: "Kg" },
  { label: "Liter", value: "Liter" },
  { label: "Unit", value: "Unit" },
  { label: "Tiket", value: "Tiket" },
  { label: "M³", value: "M³" },
  { label: "Ton/Ha", value: "Ton/Ha" },
  { label: "KWH", value: "KWH" },
  { label: "M³/Detik", value: "M³/Detik" },
  { label: "Buah", value: "Buah" },
  { label: "Set", value: "Set" },
  { label: "Paket", value: "Paket" },
  { label: "Ekor", value: "Ekor" },
  { label: "Gram", value: "Gram" },
  { label: "Ton", value: "Ton" },
  { label: "Botol", value: "Botol" },
  { label: "Ikat", value: "Ikat" },
  { label: "Lembar", value: "Lembar" },
  { label: "Tual", value: "Tual" },
  { label: "Kotak/Box", value: "Kotak/Box" },
  { label: "Tandan", value: "Tandan" },
  { label: "Mili Liter (ML)", value: "Mili Liter (ML)" },
] as const;
